puncts = [',', '.', '"', ':', ')', '(', '-', '!', '?', '|', ';', "'", '$', '&', '/', '[', ']', '>', '%', '=', '#', '*',
          '+', '\\', '•', '~', '@', '£',
          '·', '_', '{', '}', '©', '^', '®', '`', '<', '→', '°', '€', '™', '›', '♥', '←', '×', '§', '″', '′', 'Â', '█',
          '½', 'à', '…', '\xa0', '\t',
          '“', '★', '”', '–', '●', 'â', '►', '−', '¢', '²', '¬', '░', '¶', '↑', '±', '¿', '▾', '═', '¦', '║', '―', '¥',
          '▓', '—', '‹', '─', '\u3000', '\u202f',
          '▒', '：', '¼', '⊕', '▼', '▪', '†', '■', '’', '▀', '¨', '▄', '♫', '☆', 'é', '¯', '♦', '¤', '▲', 'è', '¸', '¾',
          'Ã', '⋅', '‘', '∞', '«',
          '∙', '）', '↓', '、', '│', '（', '»', '，', '♪', '╩', '╚', '³', '・', '╦', '╣', '╔', '╗', '▬', '❤', 'ï', 'Ø', '¹',
          '≤', '‡', '√', ]

mispell_dict = {"aren't": "are not",
                "can't": "cannot",
                "couldn't": "could not",
                "couldnt": "could not",
                "didn't": "did not",
                "doesn't": "does not",
                "doesnt": "does not",
                "don't": "do not",
                "hadn't": "had not",
                "hasn't": "has not",
                "haven't": "have not",
                "havent": "have not",
                "he'd": "he would",
                "he'll": "he will",
                "he's": "he is",
                "i'd": "I would",
                "i'll": "I will",
                "i'm": "I am",
                "isn't": "is not",
                "it's": "it is",
                "it'll": "it will",
                "i've": "I have",
                "let's": "let us",
                "mightn't": "might not",
                "mustn't": "must not",
                "shan't": "shall not",
                "she'd": "she would",
                "she'll": "she will",
                "she's": "she is",
                "shouldn't": "should not",
                "shouldnt": "should not",
                "that's": "that is",
                "thats": "that is",
                "there's": "there is",
                "theres": "there is",
                "they'd": "they would",
                "they'll": "they will",
                "they're": "they are",
                "theyre": "they are",
                "they've": "they have",
                "we'd": "we would",
                "we're": "we are",
                "weren't": "were not",
                "we've": "we have",
                "what'll": "what will",
                "what're": "what are",
                "what's": "what is",
                "what've": "what have",
                "where's": "where is",
                "who'd": "who would",
                "who'll": "who will",
                "who're": "who are",
                "who's": "who is",
                "who've": "who have",
                "won't": "will not",
                "wouldn't": "would not",
                "you'd": "you would",
                "you'll": "you will",
                "you're": "you are",
                "you've": "you have",
                "'re": " are",
                "wasn't": "was not",
                "we'll": " will",
                "tryin'": "trying"}

target_cols = [
    'question_asker_intent_understanding',
    'question_body_critical',
    'question_conversational',
    'question_expect_short_answer',
    'question_fact_seeking',
    'question_has_commonly_accepted_answer',
    'question_interestingness_others',
    'question_interestingness_self',
    'question_multi_intent',
    'question_not_really_a_question',
    'question_opinion_seeking',
    'question_type_choice',
    'question_type_compare',
    'question_type_consequence',
    'question_type_definition',
    'question_type_entity',
    'question_type_instructions',
    'question_type_procedure',
    'question_type_reason_explanation',
    'question_type_spelling',
    'question_well_written',
    'answer_helpful',
    'answer_level_of_information',
    'answer_plausible',
    'answer_relevance',
    'answer_satisfaction',
    'answer_type_instructions',
    'answer_type_procedure',
    'answer_type_reason_explanation',
    'answer_well_written'
]
